- include_role: {name: corpusops.roles/docker_compose_service}
  vars:
    _docker_compose_service:
      project: "{{mailman_compose_project}}"
      service_name: "{{mailman_servicename}}"
      state: "{{mailman_started_state}}"
      working_directory: "{{mailman_hostdir}}"
      stdout: "{{mailman_stdout}}"
      stderr: "{{mailman_stderr}}"
- shell: |-
    set -ex
    cd "{{mailman_hostdir}}"
    docker-compose -p {{mailman_compose_project}} up -d
  tags: [mailman_restart_services]
