---
- include_role: {name: corpusops.roles/services_virt_docker}
  tags: [docker_setup, docker_prerequisites]
- include_role: {name: mailman/service_stop}
  tags: [service, mailman_service, mailman_service_stop]
- include_role: {name: mailman/configure}
  tags: [configs, mailman_configure]
- include_role: {name: mailman/docker}
  tags: [docker_setup, docker_login, docker_pull]
- include_role: {name: mailman/service_start}
  tags: [service, mailman_service, mailman_service_start]
- include_role: {name: mailman/post}
  tags: [post]
